export enum AuditModule {
  AUTH = "auth",
  USER = "user",
  COURSE = "course",
  INSTITUTE = "institute",
  ORDER = "order",
  PAYMENT = "payment",
  ENROLLMENT = "enrollment",
  ADMISSION = "admission",
  REVIEW = "review",
  CERTIFICATE = "certificate",
  INSTRUCTOR = "instructor",
  ADMIN = "admin",
  SYSTEM = "system",
}

export enum AuditAction {
  CREATE = "create",
  READ = "read",
  UPDATE = "update",
  DELETE = "delete",
  LOGIN = "login",
  LOGOUT = "logout",
  LOGIN_FAILED = "login_failed",
  PASSWORD_RESET = "password_reset",
  EMAIL_VERIFICATION = "email_verification",
  APPROVE = "approve",
  REJECT = "reject",
  SUSPEND = "suspend",
  ACTIVATE = "activate",
  PURCHASE = "purchase",
  REFUND = "refund",
  ENROLL = "enroll",
  COMPLETE = "complete",
  EXPORT = "export",
  IMPORT = "import",
  DOWNLOAD = "download",
  UPLOAD = "upload",
}

export enum AuditSeverity {
  INFO = "info",
  WARNING = "warning",
  ERROR = "error",
  CRITICAL = "critical",
}
